name: Build & Commit Tailwind CSS

on:
  push:
    branches: [ main ]   
    paths:
      - 'input/componnets.html'
      - 'src/tw.css'
      - '.github/workflows/build-css.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
 
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # برای resolve شدن @import "tailwindcss"
      - name: Install Tailwind engine
        run: npm i -D tailwindcss@latest

      - name: Build CSS with Tailwind CLI v4
        run: |
          mkdir -p output
          npx @tailwindcss/cli@latest \
            -i ./src/tw.css \
            -o ./output/style.css \
            --minify \
            --content "./input/componnets.html"

      - name: Build output/componnets.html (wrap + link to CSS)
        shell: bash
        run: |
          mkdir -p output
          {
            echo '<!doctype html>'
            echo '<html lang="en">'
            echo '<head>'
            echo '  <meta charset="utf-8" />'
            echo '  <meta name="viewport" content="width=device-width,initial-scale=1" />'
            echo '  <title>Components</title>'
            echo '  <link rel="stylesheet" href="./style.css" />'
            echo '</head>'
            echo '<body>'
            echo '  <main>'
            cat input/componnets.html || true
            echo '  </main>'
            echo '</body>'
            echo '</html>'
          } > output/componnets.html

      - name: Commit & push output files
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/style.css output/componnets.html
          git diff --cached --quiet && echo "No changes" && exit 0
          git commit -m "chore: build output (style.css + componnets.html) [skip ci]"
          git push
